BEGIN TRANSACTION;
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (1, '70% Off on genuine Indian dish', 'We promise you best genuine indian taste in city. Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.
Dumy lines to increase size of paragraph.', 1, 70, 1, 2, 2, 1, '1', '1', '2018-04-18', '2013-04-18 13:02:54', '2013-04-21 12:21:37', 1, 'indian_dish.jpg', 2);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (2, '53% Discount on continental Salad', 'Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.53% Discount on continental Salad', 2, 53, 1, 2, 2, 1, '1', '1', '2018-11-19', '2013-04-19 01:10:16', '2013-04-21 12:22:54', 1, 'continetal_salad.jpg', 3);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (3, '80% Off on Diet items', 'Dumy lines to increase size of paragraph. 80% Off on Diet items suggested by our dietitians', 3, 80, 1, 1, 2, 1, '1', '1', '2016-07-16', '2013-04-19 01:11:43', '2013-04-21 12:27:05', 1, 'diet_food.jpg', 4);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (4, '90% Off on second dosa', 'second dosa on monday. Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.', 4, 90, 1, 3, 2, 1, '1', '1', '2018-05-20', '2013-04-19 01:12:59', '2013-04-21 12:28:25', 1, 'dosa.jpg', 5);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (5, '15% offer on new dishes', 'Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.', 5, 15, 1, 1, 2, 1, '1', '1', '2018-12-20', '2013-04-19 01:15:01', '2013-04-21 12:30:11', 1, 'chichen.jpg', 1);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (6, '60% off on weekend feast', 'Dummy Description', 6, 60, 1, 2, 2, 1, '1', '1', '2018-12-30', '2013-04-19 01:16:04', '2013-04-21 12:31:02', 1, 'feast.jpg', 2);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (7, '40% off special noodles', 'Dumy lines to increase size of paragraph. Spedcial noodeles', 33, 40, 1, 2, 2, 1, '1', '1', '2018-12-20', '2013-04-19 12:19:45', '2013-04-21 12:34:56', 1, 'noodles.jpg', 3);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (8, 'Have feast and take 30% off', 'Dumy lines to increase size of paragraph. Enjoy feast', 33, 30, 1, 2, 2, 1, '0', '0', '2013-04-21', '2013-04-21 12:33:17', '2013-04-21 12:33:17', 1, 'festival.jpg', 4);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (9, '50% off at Souvlaki Hut', 'Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.Dumy lines to increase size of paragraph.', 33, 50, 1, 2, 2, 1, '0', '0', '2013-04-21', '2013-04-21 12:38:20', '2013-04-21 12:38:52', 5, 'Souvlaki_Hut.jpg', 5);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (10, 'Up to 65% off Organic Matcha', 'Dumy lines to increase size of paragraph. Up to 65% off Organic Matcha. Dumy lines to increase size of paragraph. Up to 65% off Organic Matcha. Dumy lines to increase size of paragraph. Up to 65% off Organic Matcha. 
Dumy lines to increase size of paragraph. Up to 65% off Organic Matcha. 
Dumy lines to increase size of paragraph. Up to 65% off Organic Matcha. ', 33, 65, 1, 2, 2, 1, '0', '0', '2013-04-21', '2013-04-21 12:42:19', '2013-04-21 12:56:35', 5, 'Organic_Matcha.jpg', 1);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (11, '10% off on exotic sea food', 'Dumy lines to increase size of paragraph. 10% off on exotic sea food. Dumy lines to increase size of paragraph. 10% off on exotic sea food. Dumy lines to increase size of paragraph. 10% off on exotic sea food. Dumy lines to increase size of paragraph. 10% off on exotic sea food. 
Dumy lines to increase size of paragraph. 10% off on exotic sea food. ', 33, 10, 1, 2, 2, 1, '0', '0', '2016-04-21', '2013-04-21 12:43:35', '2013-04-21 12:43:35', 5, 'sea_food.jpg', 2);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (12, '10% off on exotic sea food', 'Dumy lines to increase size of paragraph. 10% off on exotic sea food. ', 33, 10, 2, 2, 2, 1, '0', '0', '2016-04-21', '2013-04-21 12:43:52', '2013-04-21 12:43:52', 5, 'sea_food.jpg', 3);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (13, '70% Off on medium pizza', '70% Off on medium pizza with every large size pizza. Dumy lines to increase size of paragraph. 70% Off on medium pizza with every large size pizza. 70% Off on medium pizza with every large size pizza. Dumy lines to increase size of paragraph. 70% Off on medium pizza with every large size pizza70% Off on medium pizza with every large size pizza. Dumy lines to increase size of paragraph. 70% Off on medium pizza with every large size pizza', 33, 70, 1, 2, 2, 1, '0', '0', '2013-04-21', '2013-04-21 12:45:16', '2013-04-21 12:45:16', 5, 'pizza.jpg', 4);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (14, '60% off Gourmet Lollipops', 'Luckily for the lollipop industry, there''s a sucker born every minute. Set up your own in-home candy bar with this WagJag: $29 for 60 gourmet lollipops (a $72 value).

These long-lasting candies provide sweet satisfaction with their golf ball size and vibrant colour. Each package of 60 individually wrapped, USA-made pops contains an array of mouth-watering flavours. But just what flavour each one is will have to be determined by your tongue - this bounty of bonbons are labeled only as "Mystery Flavour" and each box contains a random assortment. To help solve the candy conundrum, here is the complete list:', 33, 65, 1, 2, 2, 1, '1', '1', '2013-04-21', '2013-04-21 12:50:16', '2013-04-21 12:57:11', 5, 'Gourmet_Lollipops.jpg', 5);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (15, '50 % on ATV rental', 'ATVs are capable of travelling over any land surface, though people usually don''t appreciate it when you use them inside the house, through the maternity ward of a hospital or down the aisle at your wedding. Ride free of social judgment with today''s WagJag: $59 for a one-hour ATV adventure from Ride on Rentals (a $120 value).

Already a specialist in providing exciting outdoor excursions throughout the rugged Collingwood landscape, Ride on Rentals has expanded their fleet of land and water vehicles to now include a collection of newly minted, state-of-the-art all-terrain vehicles (ATVs) for speedy summer amusement. Hop on board solo, or bring a friend along on a two-person unit, and get ready to gun it through the massive network of interconnected trails located in Bruce County''s 600 acres of hardwood forest. Ride on Rentals provides the vehicles, helmets and basic operation instruction before setting you off on your journey. As an optional bonus, this offer includes a $20 credit towards a two-person kayaking rental to explore the serene waters of the Georgian Bay.', 31, 50, 1, 2, 2, 1, '0', '0', '2013-04-21', '2013-04-21 12:59:21', '2013-04-21 12:59:21', 5, 'ATV.jpg', 1);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (16, 'Up to 52% off EkoBrew Pods', 'Like stopping to eat the flowers or having your eyebrows brushed by a loved one, a fresh cup of coffee is one of life''s simple pleasures. Marry a love of java with love for the environment in EkoBrew''s reusable single-cup coffee pods. Designed for and compatible with most Keurig single-cup machines, EkoBrew pods can be filled with the grounds of your choice, then brewed with the touch of a button. Using a low tamp dispersion cone, coffee grounds are gently and evenly saturated for optimal extraction. Features like a heat-resistant silicone seal, easy-open lid, stainless steel mesh screen and flat-bottom design are convenient and user-friendly. A quick rinse after use and a weekly soak in dilute vinegar water keeps EkoBrew pods clean and free of residue.', 14, 52, 1, 2, 2, 1, '0', '0', '2013-04-21', '2013-04-21 13:01:12', '2013-04-21 13:01:12', 5, 'ekoBrew.jpg', 2);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (17, 'Radio Advertising centre', 'This is one of popular advertising agency in canada.', 13, 12, 1, 1, 1, 1, '1', '1', '2013-05-02', '2013-05-02 07:07:17', '2013-06-08 13:02:42', 1, 'radio.jpg', 3);
INSERT INTO ads ("id", "title", "description", "ad_category_id", "price", "address_id", "company_id", "shopping_mall_id", "ad_position_id", "ispublished", "isapproved", "expiry_date", "created_at", "updated_at", "user_id", "image", "ad_type_id") VALUES (18, 'Ironman Toy', 'New Ironman steelmade toy', 31, 10, 1, 5, 1, 1, '0', NULL, '2013-05-15', '2013-05-15 18:58:23', '2013-06-08 13:03:51', 8, 'ironman_toy.jpg', 4);
COMMIT;
