BEGIN TRANSACTION;
INSERT INTO shopping_malls ("id", "name", "description", "mall_type_id", "ispublished", "created_at", "updated_at", "image", "address_id") VALUES (1, 'Eaton Centre', 'Eaton Centre', 1, '0', '2013-04-19 14:00:10', '2013-04-21 14:20:14', 'shoping_mall.jpg', 16);
INSERT INTO shopping_malls ("id", "name", "description", "mall_type_id", "ispublished", "created_at", "updated_at", "image", "address_id") VALUES (2, 'Mark value', '', 2, '0', '2013-04-19 14:00:33', '2013-04-21 14:22:25', 'mark_value.jpg', 12);
INSERT INTO shopping_malls ("id", "name", "description", "mall_type_id", "ispublished", "created_at", "updated_at", "image", "address_id") VALUES (3, 'Iranian Plaza', '', 2, '0', '2013-04-19 14:00:55', '2013-04-21 14:24:40', 'Iranian_Plaza.jpg', 13);
INSERT INTO shopping_malls ("id", "name", "description", "mall_type_id", "ispublished", "created_at", "updated_at", "image", "address_id") VALUES (6, 'Relience', '', 2, '0', '2013-04-19 14:02:37', '2013-04-21 14:26:07', 'reliance_cananda.jpg', 14);
INSERT INTO shopping_malls ("id", "name", "description", "mall_type_id", "ispublished", "created_at", "updated_at", "image", "address_id") VALUES (7, 'Fairview Mall', 'Fairview Mall is a major shopping centre in Toronto, Ontario, Canada of about 80,000 m² (900,000 ft2), located at the northeast corner of Don Mills Road and Sheppard Avenue East in the former borough of North York. In early 2009 it was jointly owned by Cadillac Fairview (50%) and Ivanhoe Cambridge (50%), two of Canada''s largest real estate property managers and developers.', 2, '0', '2013-05-24 11:29:07', '2013-05-24 11:32:50', 'fairview.jpeg', 6);
INSERT INTO shopping_malls ("id", "name", "description", "mall_type_id", "ispublished", "created_at", "updated_at", "image", "address_id") VALUES (8, 'Scarborough Town Centre', 'The Scarborough Town Centre is a shopping mall in the Scarborough district of Toronto, Ontario, Canada. Central to the Scarborough City Centre, it is adjacent to the Scarborough Centre RT station and Scarborough Centre Bus Terminal.[2] It was constructed by Oxford Properties and opened in 1973 to become the ninth largest shopping mall in Canada, fifth largest in Ontario and third in Toronto by retail space, making it one of the five major shopping malls in Toronto.', 1, '0', '2013-05-24 11:32:03', '2013-05-24 11:32:21', 'scarborough_town_centre_balloons4.jpg', 17);
INSERT INTO shopping_malls ("id", "name", "description", "mall_type_id", "ispublished", "created_at", "updated_at", "image", "address_id") VALUES (9, 'Sherway Gardens', 'Sherway Gardens is an upscale shopping mall originally built in 1971 in the west end area of Toronto known as Etobicoke.The mall''s original structure covered 850,000 square feet (79,000 m2) and contained 127 stores. Sherway Gardens was subsequently expanded to 972,540 square feet (90,352 m2) with 215 stores, becoming the eighth largest mall in the Greater Toronto Area. It is a terminus for several Toronto Transit Commission and MiWay bus routes.', 2, '0', '2013-05-24 11:34:23', '2013-05-24 11:35:41', '200px-Sherway_Gardens_Entrance_7.jpg', 9);
COMMIT;
